### ISSUE TITLE
BioC2021 check: GitHub Action failing

### ISSUE THREAD

**Issue by kevinrue** [kstreet13/bioc2020trajectories#1]
Hi there,

Just doing the rounds tonight. I noticed that you've got an issue installing `DelayedMatrixStats` during the GitHub Action workflow. Have you got an action plan to tackle that? Perhaps you just need to re-run the workflow again, since the last time it ran seems to be before the latest BioC release.

Let me know if you need any help of advice!
Kevin, (BioC2021 committee)

**Comment by kstreet13** [comment]
Hey Kevin,

Yeah, I've seen that issue a few times now and it seems to have been fixed with the latest release. Also, just so we're on the same page, we have an [updated version of the workshop](https://github.com/HectorRDB/bioc2021trajectories) that we are planning on using for BioC2021.

Best,
Kelly

**Comment by kevinrue** [comment]
Woops - I didn't realise that I was pointing to the 2020 version. (Can't seem to get over that year :P )
